id: P009326
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:33:36.930545
source_metadata:
  id: bdr:W8LS17241
  title: ཞིང་མཆོག་རྟེན་གསུམ་ལ་རབ་གནས་བྱེད་ཚུལ་དང་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ལུགས་ཀྱི་ཞི་བའི་སྦྱིན་སྲེག་ཆོ་ག
  author: ''
  volumes:
    1536c0fb5fee4e5eb5445f28dbae8823:
      image_group_id: I8LS17270
      title: ''
      volume_number: 1
      total_pages: 64
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
