id: opecha:P009326
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17241
  title: ཞིང་མཆོག་རྟེན་གསུམ་ལ་རབ་གནས་བྱེད་ཚུལ་དང་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ལུགས་ཀྱི་ཞི་བའི་སྦྱིན་སྲེག་ཆོ་ག
  volume: ''
  author: ''
