id: IF069909D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:39:14+00:00'
last_modified: '2022-06-08T10:13:27.040838+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17241
  title: ཞིང་མཆོག་རྟེན་གསུམ་ལ་རབ་གནས་བྱེད་ཚུལ་དང་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ལུགས་ཀྱི་ཞི་བའི་སྦྱིན་སྲེག་ཆོ་ག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC10:
      image_group_id: I8LS17270
      title: ''
      total_pages: 64
      order: 1
      base_file: CC10.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
