id: IF069909D
legacy_id: P009326
ocr_import_info:
  bdrc_scan_id: W8LS17241
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:38:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:44:49.943152+00:00'
last_modified: 2022-09-04 11:44:55.048586
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17241
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17241
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞིང་མཆོག་རྟེན་གསུམ་ལ་རབ་གནས་བྱེད་ཚུལ་དང་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ལུགས་ཀྱི་ཞི་བའི་སྦྱིན་སྲེག་ཆོ་ག
statistics:
  ocr_word_mean_confidence_index: 0.6485362739566226
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I8LS17270:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17270
      total_pages: 64
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17270.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6485362739566226
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
